latest_epel_repo: "http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm"
rhel_72_ami: ami-4dbf9e7d
region: us-west-2

security_group: vault-consul-starter

hosts:
  haproxy:
    instance: t2.medium
    user: ec2-user
    image: "{{ rhel_72_ami }}"
  vault:
    image: "{{ rhel_72_ami }}"
    instance: t2.medium
    user: ec2-user