haproxy:
  default: vault
  health_check_port: 8200
  health_check_url: /v1/sys/health
  ports_to_open:
    - port: 8200
    - port: 1936
  backends:
    - title: vault
      servers:
        - title: "{{ hostvars[groups.tag_vault_host[0]].ec2_ip_address }}"
          address: "{{ hostvars[groups.tag_vault_host[0]].ec2_private_ip_address }}"
          port: 8200
        - title: "{{ hostvars[groups.tag_vault_host[1]].ec2_ip_address }}"
          address: "{{ hostvars[groups.tag_vault_host[1]].ec2_private_ip_address }}"
          port: 8200
        - title: "{{ hostvars[groups.tag_vault_host[2]].ec2_ip_address }}"
          address: "{{ hostvars[groups.tag_vault_host[2]].ec2_private_ip_address }}"
          port: 8200