---
- name: reload systemd
  become: yes
  command: systemctl daemon-reload
      
- name: restart consul
  action: service name=consul state=restarted enabled=yes

- name: reload consul config
  become: yes
  command: pkill -1 consul
