---
# Vault must be unsealed every time it is started.
# Expects key1 key2 key3 to be provided as extra-vars.

- name: Unseal the vaults
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: vault_unseal
