# Initialize vault.  Only needs to be done once.  Make sure to record the keys returned.
- hosts: tag_Name_vault
  remote_user: ec2-user
  vars:
    - ansible_ssh_user: "{{ hosts.vault.user }}"
  roles:
    - role: vault_init