---

- name: Install OS Packages
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python

- group: name=keyrotator state=present

- user: name=keyrotator group=keyrotator

- name: create the target directories for the application
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: 0755
    owner: keyrotator
    group: keyrotator

- name: Download application jar
  get_url:
    url: "{{ nexus.address }}/{{ nexus.maven_content_service}}?g={{ deployable.group_id }}&a={{ deployable.artifact_id }}&v={{ deployable.version }}&r={{ deployable.repository }}"
    url_username: "{{ nexus.credentials.username }}"
    url_password: "{{ nexus.credentials.password }}"
    validate_certs: no
    dest: "{{ install_dir }}/{{ application_file }}"
    owner: keyrotator
    group: keyrotator
    mode: 0750
  notify:
  - restart keyrotator services

- name: Copy log4j2.xml
  template:
    src: log4j2.xml.j2
    dest: "{{ install_dir }}/log4j2.xml"
    mode: 0640
    owner: keyrotator
    group: keyrotator
  notify:
      - reload systemd
      - restart keyrotator services

- name: systemd service
  template:
    src: keyrotator.service.j2
    dest: "/etc/systemd/system/keyrotator.service"
    mode: 0750
    owner: keyrotator
    group: keyrotator
  notify:
      - reload systemd
      - restart keyrotator services