- name: "Enable Vault Audit"
  sudo: false
  local_action:
    module: uri
    validate_certs: no
    method: PUT
    status_code: 204
    return_content: yes
    HEADER_X-Vault-Token: "{{ key1 }}"
    url: https://{{ ec2_private_dns_name }}/v1/sys/audit/file
    body: '{"type": "file", "options": {"path": "/var/log/vault/vault_audit.log"}}'
  register: json_response

- name: "Output response"
  debug: var=json_response
  
- name: "Mount Vault Transit Backend"
  sudo: false
  local_action:
    module: uri
    validate_certs: no
    method: PUT
    status_code: 204
    return_content: yes
    HEADER_X-Vault-Token: "{{ key1 }}"
    url: https://{{ ec2_private_dns_name }}/v1/sys/mounts/transit
    body: '{"type":"transit"}'
  register: json_response

- name: "Output response"
  debug: var=json_response
  
- name: "Create Vault Transit Key"
  sudo: false
  local_action:
    module: uri
    validate_certs: no
    method: POST
    status_code: 204
    return_content: yes
    HEADER_X-Vault-Token: "{{ key1 }}"
    url: https://{{ ec2_private_dns_name }}/v1/transit/keys/key
  register: json_response

- name: "Output response"
  debug: var=json_response