- name: Create a security group
  local_action: 
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group for Vault / Consul starter
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
      - proto: udp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
      - proto: udp
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0