---
vault:
  download_file: vault_0.6.0_linux_amd64.zip
  port: 8200
  
ssl_certs:
  subject_alt_names: 
    - "{{ ansible_fqdn }}"
    - "{{ hostvars[groups.tag_haproxy_vault_host[0]].ec2_private_ip_address }}"

filebeat:
  prospector_conf: vault.yml
  prospectors:
    -
      paths:
        - /var/log/vault/vault_audit.log
      type: log
      document_type: json_log
      fields:
        -
          name: type
          value: vault
        -
          name: application
          value: vault