---
 - name: Ensure SSL Conf File is Configured
   template: "src=openssl.cnf.j2 dest={{ ssl_working_dir }}/gen_openssl.cnf owner={{ ssl_certs_path_owner }} group={{ ssl_certs_path_group }} mode=644"
 
 - name: Setup index
   shell: "touch {{ ssl_working_dir }}/index"
   
 - name: Setup chain ca
   shell: "touch {{ ssl_working_dir }}/chain-ca.crt"
   
 - name: Setup serial
   shell: "echo 1000 > {{ ssl_working_dir }}/serial"
 
 - name: Ensure subordinate CA conf is present
   copy: "src={{ ssl_local_sub_ca_cnf_path }} dest={{ ssl_working_dir }}/sub-ca.cnf owner={{ ssl_certs_path_owner }} group={{ ssl_certs_path_group }} mode=600"

 - name: Ensure subordinate CA cert is present
   copy: "src={{ ssl_local_sub_ca_path }} dest={{ ssl_working_dir }}/sub-ca.crt owner={{ ssl_certs_path_owner }} group={{ ssl_certs_path_group }} mode=600"
 
 - name: Ensure root CA cert is present
   copy: "src={{ ssl_local_root_ca_path }} dest={{ ssl_working_dir }}/root-ca.crt owner={{ ssl_certs_path_owner }} group={{ ssl_certs_path_group }} mode=644"
   
 - name: Copy over subordinate CA private key
   copy: "content={{ secrets.certs.sub_ca_private_key }} dest={{ ssl_working_dir }}/sub-ca.key"

 - name: Generate RSA key
   command: "openssl genrsa -out {{ ssl_certs_privkey_path }} {{ ssl_certs_key_size }}"

 - name: Generate CSR
   command: "openssl req -new -subj '{{ ssl_certs_fields }}' -key {{ ssl_certs_privkey_path }} -out {{ ssl_certs_csr_path }} -config {{ ssl_working_dir }}/gen_openssl.cnf"

 - name: Sign CSR with Subordinate CA
   command: "openssl ca -batch -config {{ ssl_working_dir }}/sub-ca.cnf -extensions server_ext -notext -in {{ ssl_certs_csr_path }} -key {{ secrets.certs.sub_ca_private_key_password }} -out {{ ssl_certs_cert_path }}"
     
 - name: Add subordinate CA cert to server cert
   shell: "cat {{ ssl_working_dir }}/sub-ca.crt >> {{ ssl_certs_cert_path }}"
   
 - name: Add subordinate CA cert to chain ca
   shell: "cat {{ ssl_working_dir }}/sub-ca.crt >> {{ ssl_certs_chain_ca_path }}"
   
 - name: Add root CA cert to chain ca
   shell: "cat {{ ssl_working_dir }}/root-ca.crt >> {{ ssl_certs_chain_ca_path }}"
     
 - name: Remove private key after done using
   file: "path={{ ssl_working_dir }}/sub-ca.key state=absent"
   
 - name: Remove index after done using
   file: "path={{ ssl_working_dir }}/index state=absent"
   
 - name: Remove serial after done using
   file: "path={{ ssl_working_dir }}/serial state=absent"
