- name: "Initialize Vault"
  local_action:
    module: uri
    validate_certs: no
    method: PUT
    status_code: 200
    return_content: yes
    url: https://{{ ec2_private_dns_name }}:{{ vault.port }}/v1/sys/init
    body: '{"secret_shares": 5,"secret_threshold": 3}'
  register: json_response

- name: "Output response"
  debug: var=json_response